# comment if you don't want dynamic framework
use_frameworks!

platform :ios, '16.0'
### original
target 'pod1_Example' do
  pod 'pod1', :path => '../'
  
  target 'pod1_Tests' do
    inherit! :search_paths
      
  end
end
